# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 20
  - name: News
    url: '#posts'
    weight: 30
  - name: Resources
    url: '#resources'
    weight: 40
  - name: Projects
    url: '#projects'
    weight: 50
  - name: Talks
    url: '#talks'
    weight: 60
  - name: Students
    url: '/students'
    weight: 65

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
